# 3. Keras + TensorFlow
### Practice Notebook
---
*by Pablo Bauer*

#### Import libraries

In [ ]:
import tensorflow as tf
x = tf.ones(shape=(2,1))

In [ ]:
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [ ]:
x = tf.zeros(shape=(2,1))

In [ ]:
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(shape=(3,1), mean=0., stddev=1.)

In [ ]:
print(random_tensor)

tf.Tensor(
[[-0.9428334]
 [ 1.1459739]
 [ 1.0967115]], shape=(3, 1), dtype=float32)


In [ ]:
variable = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
variable

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.89163136],
       [-0.52555245],
       [-0.55034304]], dtype=float32)>

In [ ]:
variable.assign(tf.ones(shape=(3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
variable[0,0].assign((3))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

In [ ]:
variable.assign_add(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

In [ ]:
variable

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>