# "HOLA MUNDO" DEL DEEP LEARNING
### Con TensorFlow + Keras

---

### 2.1  Cargando los datos de MNIST en Keras

In [17]:
from tensorflow.keras.datasets import mnist

In [5]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [6]:
train_images.shape

(60000, 28, 28)

In [7]:
len(train_labels)

60000

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
test_images.shape

(10000, 28, 28)

In [12]:
len(test_images)

10000

In [14]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

### 2.2 La arquitectura de la red

In [15]:
from tensorflow import keras
from tensorflow.keras import layers

**Optimizador** mecanismo por donde el modelo se retroaliminetara y se actualizará, basado en el dataset de entrenamiento.
**Función de perdidad (loss function)** Como se medirá el modelo asi mimsmo con el data set de entrenamiento.
**Metricas** Como medir la exactitud del modelo. 

In [16]:
model = keras.Sequential([layers.Dense(512, activation='relu'),layers.Dense(10,activation='softmax')])

### 2.3 Compilando el modelo

In [21]:
model.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

### 2.4 Preparando los datos de las imagenes

In [22]:
train_images = train_images.reshape((60000, 28 *28))
train_images = train_images.astype('float32')/255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32')/255

### 2.5 Fiteando el modelo con Keras

In [25]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 8ms/step - loss: 0.3824 - accuracy: 0.8928
Epoch 2/5
469/469 [==============================] - 4s 8ms/step - loss: 0.3706 - accuracy: 0.8949
Epoch 3/5
469/469 [==============================] - 3s 7ms/step - loss: 0.3604 - accuracy: 0.8975
Epoch 4/5
469/469 [==============================] - 3s 7ms/step - loss: 0.3523 - accuracy: 0.8992
Epoch 5/5
469/469 [==============================] - 4s 8ms/step - loss: 0.3448 - accuracy: 0.9007


In [26]:
test_digits = test_images[0:10]

In [27]:
predictions = model.predict(test_digits)

1/1 [==============================] - 0s 124ms/step


In [28]:
predictions[0]

array([4.6956273e-05, 7.2311877e-08, 2.0081616e-05, 2.4688576e-04,
       1.0981084e-06, 1.9876794e-05, 4.8684932e-09, 9.9815398e-01,
       4.0309010e-06, 1.5068548e-03], dtype=float32)

In [30]:
predictions[0].argmax()

7

In [31]:
predictions[0][7]

0.998154

In [32]:
test_labels[0]

7

### 2.7 Evaluando el modelo con nueva data

In [33]:
test_loss, test_acc = model.evaluate(test_images, test_labels)

313/313 [==============================] - 2s 3ms/step - loss: 0.3262 - accuracy: 0.9047


In [35]:
print(f'test_acc: {test_acc}')
print(f'test_loss: {test_loss}')

test_acc: 0.904699981212616
test_loss: 0.3262336254119873


### 2.2.5 Displaying the fourth digit

In [37]:
import matplotlib.pyplot as plt

In [44]:
digit = train_images[4]
#plt.imshow(digit, cmap=plt.cm.binary)

In [40]:
train_labels[4]

9